//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.06 at 05:50:06 PM GMT+07:00 
//


package org.netbeans.modules.websvc.saas.model.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Authenticator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Authenticator"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="use-templates" type="{http://xml.netbeans.org/websvc/saas/services/1.0}UseTemplates" minOccurs="0"/&gt;
 *         &lt;element name="use-generator" type="{http://xml.netbeans.org/websvc/saas/services/1.0}UseGenerator" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="xref" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Authenticator", propOrder = {
    "useTemplates",
    "useGenerator"
})
@XmlSeeAlso({
    org.netbeans.modules.websvc.saas.model.jaxb.SaasMetadata.Authentication.Authenticator.class
})
public class Authenticator {

    @XmlElement(name = "use-templates")
    protected UseTemplates useTemplates;
    @XmlElement(name = "use-generator")
    protected UseGenerator useGenerator;
    @XmlAttribute(name = "xref")
    protected String xref;

    /**
     * Gets the value of the useTemplates property.
     * 
     * @return
     *     possible object is
     *     {@link UseTemplates }
     *     
     */
    public UseTemplates getUseTemplates() {
        return useTemplates;
    }

    /**
     * Sets the value of the useTemplates property.
     * 
     * @param value
     *     allowed object is
     *     {@link UseTemplates }
     *     
     */
    public void setUseTemplates(UseTemplates value) {
        this.useTemplates = value;
    }

    /**
     * Gets the value of the useGenerator property.
     * 
     * @return
     *     possible object is
     *     {@link UseGenerator }
     *     
     */
    public UseGenerator getUseGenerator() {
        return useGenerator;
    }

    /**
     * Sets the value of the useGenerator property.
     * 
     * @param value
     *     allowed object is
     *     {@link UseGenerator }
     *     
     */
    public void setUseGenerator(UseGenerator value) {
        this.useGenerator = value;
    }

    /**
     * Gets the value of the xref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXref() {
        return xref;
    }

    /**
     * Sets the value of the xref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXref(String value) {
        this.xref = value;
    }

}
