//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.06 at 05:50:06 PM GMT+07:00 
//


package org.netbeans.modules.websvc.saas.model.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MethodDescriptor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MethodDescriptor"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="modifiers" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="return-type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="throws" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="body" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="body-ref" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="param-types" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="param-names" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MethodDescriptor")
public class MethodDescriptor {

    @XmlAttribute(name = "modifiers")
    protected String modifiers;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "return-type")
    protected String returnType;
    @XmlAttribute(name = "throws")
    protected String _throws;
    @XmlAttribute(name = "body")
    protected String body;
    @XmlAttribute(name = "body-ref")
    protected String bodyRef;
    @XmlAttribute(name = "param-types")
    protected String paramTypes;
    @XmlAttribute(name = "param-names")
    protected String paramNames;

    /**
     * Gets the value of the modifiers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiers() {
        return modifiers;
    }

    /**
     * Sets the value of the modifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiers(String value) {
        this.modifiers = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the returnType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnType() {
        return returnType;
    }

    /**
     * Sets the value of the returnType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnType(String value) {
        this.returnType = value;
    }

    /**
     * Gets the value of the throws property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThrows() {
        return _throws;
    }

    /**
     * Sets the value of the throws property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThrows(String value) {
        this._throws = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBody(String value) {
        this.body = value;
    }

    /**
     * Gets the value of the bodyRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBodyRef() {
        return bodyRef;
    }

    /**
     * Sets the value of the bodyRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBodyRef(String value) {
        this.bodyRef = value;
    }

    /**
     * Gets the value of the paramTypes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParamTypes() {
        return paramTypes;
    }

    /**
     * Sets the value of the paramTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParamTypes(String value) {
        this.paramTypes = value;
    }

    /**
     * Gets the value of the paramNames property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParamNames() {
        return paramNames;
    }

    /**
     * Sets the value of the paramNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParamNames(String value) {
        this.paramNames = value;
    }

}
