//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.06 at 05:50:06 PM GMT+07:00 
//


package org.netbeans.modules.websvc.saas.model.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SaasMetadata complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SaasMetadata"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="localizing-bundle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://xml.netbeans.org/websvc/saas/services/1.0}group"/&gt;
 *         &lt;element name="code-gen" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="artifacts" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Artifacts" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="packageName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="authentication" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="authenticator" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;extension base="{http://xml.netbeans.org/websvc/saas/services/1.0}Authenticator"&gt;
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;choice&gt;
 *                     &lt;element name="http-basic"&gt;
 *                       &lt;complexType&gt;
 *                         &lt;complexContent&gt;
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                             &lt;sequence&gt;
 *                               &lt;element name="authenticator" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Authenticator"/&gt;
 *                             &lt;/sequence&gt;
 *                             &lt;attribute name="username" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                             &lt;attribute name="password" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;/restriction&gt;
 *                         &lt;/complexContent&gt;
 *                       &lt;/complexType&gt;
 *                     &lt;/element&gt;
 *                     &lt;element name="api-key"&gt;
 *                       &lt;complexType&gt;
 *                         &lt;complexContent&gt;
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                             &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;/restriction&gt;
 *                         &lt;/complexContent&gt;
 *                       &lt;/complexType&gt;
 *                     &lt;/element&gt;
 *                     &lt;element name="signed-url" maxOccurs="unbounded" minOccurs="0"&gt;
 *                       &lt;complexType&gt;
 *                         &lt;complexContent&gt;
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                             &lt;sequence&gt;
 *                               &lt;element name="sign" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Sign" minOccurs="0"/&gt;
 *                               &lt;element name="authenticator" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Authenticator" minOccurs="0"/&gt;
 *                             &lt;/sequence&gt;
 *                             &lt;attribute name="sig-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                             &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;/restriction&gt;
 *                         &lt;/complexContent&gt;
 *                       &lt;/complexType&gt;
 *                     &lt;/element&gt;
 *                     &lt;element name="session-key" maxOccurs="unbounded" minOccurs="0"&gt;
 *                       &lt;complexType&gt;
 *                         &lt;complexContent&gt;
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                             &lt;sequence&gt;
 *                               &lt;element name="sign" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Sign"/&gt;
 *                               &lt;element name="authenticator" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Authenticator"/&gt;
 *                             &lt;/sequence&gt;
 *                             &lt;attribute name="session-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                             &lt;attribute name="api-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                             &lt;attribute name="sig-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                             &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;/restriction&gt;
 *                         &lt;/complexContent&gt;
 *                       &lt;/complexType&gt;
 *                     &lt;/element&gt;
 *                     &lt;element name="custom" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                   &lt;/choice&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="profile" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SaasMetadata", propOrder = {
    "localizingBundle",
    "group",
    "codeGen",
    "authentication"
})
public class SaasMetadata {

    @XmlElement(name = "localizing-bundle")
    protected String localizingBundle;
    @XmlElement(required = true)
    protected Group group;
    @XmlElement(name = "code-gen")
    protected SaasMetadata.CodeGen codeGen;
    protected SaasMetadata.Authentication authentication;

    /**
     * Gets the value of the localizingBundle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalizingBundle() {
        return localizingBundle;
    }

    /**
     * Sets the value of the localizingBundle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalizingBundle(String value) {
        this.localizingBundle = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link Group }
     *     
     */
    public Group getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link Group }
     *     
     */
    public void setGroup(Group value) {
        this.group = value;
    }

    /**
     * Gets the value of the codeGen property.
     * 
     * @return
     *     possible object is
     *     {@link SaasMetadata.CodeGen }
     *     
     */
    public SaasMetadata.CodeGen getCodeGen() {
        return codeGen;
    }

    /**
     * Sets the value of the codeGen property.
     * 
     * @param value
     *     allowed object is
     *     {@link SaasMetadata.CodeGen }
     *     
     */
    public void setCodeGen(SaasMetadata.CodeGen value) {
        this.codeGen = value;
    }

    /**
     * Gets the value of the authentication property.
     * 
     * @return
     *     possible object is
     *     {@link SaasMetadata.Authentication }
     *     
     */
    public SaasMetadata.Authentication getAuthentication() {
        return authentication;
    }

    /**
     * Sets the value of the authentication property.
     * 
     * @param value
     *     allowed object is
     *     {@link SaasMetadata.Authentication }
     *     
     */
    public void setAuthentication(SaasMetadata.Authentication value) {
        this.authentication = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="authenticator" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;extension base="{http://xml.netbeans.org/websvc/saas/services/1.0}Authenticator"&gt;
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;choice&gt;
     *           &lt;element name="http-basic"&gt;
     *             &lt;complexType&gt;
     *               &lt;complexContent&gt;
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                   &lt;sequence&gt;
     *                     &lt;element name="authenticator" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Authenticator"/&gt;
     *                   &lt;/sequence&gt;
     *                   &lt;attribute name="username" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                   &lt;attribute name="password" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;/restriction&gt;
     *               &lt;/complexContent&gt;
     *             &lt;/complexType&gt;
     *           &lt;/element&gt;
     *           &lt;element name="api-key"&gt;
     *             &lt;complexType&gt;
     *               &lt;complexContent&gt;
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                   &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;/restriction&gt;
     *               &lt;/complexContent&gt;
     *             &lt;/complexType&gt;
     *           &lt;/element&gt;
     *           &lt;element name="signed-url" maxOccurs="unbounded" minOccurs="0"&gt;
     *             &lt;complexType&gt;
     *               &lt;complexContent&gt;
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                   &lt;sequence&gt;
     *                     &lt;element name="sign" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Sign" minOccurs="0"/&gt;
     *                     &lt;element name="authenticator" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Authenticator" minOccurs="0"/&gt;
     *                   &lt;/sequence&gt;
     *                   &lt;attribute name="sig-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                   &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;/restriction&gt;
     *               &lt;/complexContent&gt;
     *             &lt;/complexType&gt;
     *           &lt;/element&gt;
     *           &lt;element name="session-key" maxOccurs="unbounded" minOccurs="0"&gt;
     *             &lt;complexType&gt;
     *               &lt;complexContent&gt;
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                   &lt;sequence&gt;
     *                     &lt;element name="sign" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Sign"/&gt;
     *                     &lt;element name="authenticator" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Authenticator"/&gt;
     *                   &lt;/sequence&gt;
     *                   &lt;attribute name="session-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                   &lt;attribute name="api-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                   &lt;attribute name="sig-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                   &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;/restriction&gt;
     *               &lt;/complexContent&gt;
     *             &lt;/complexType&gt;
     *           &lt;/element&gt;
     *           &lt;element name="custom" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *         &lt;/choice&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="profile" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "authenticator",
        "httpBasic",
        "apiKey",
        "signedUrl",
        "sessionKey",
        "custom"
    })
    public static class Authentication {

        protected List<SaasMetadata.Authentication.Authenticator> authenticator;
        @XmlElement(name = "http-basic")
        protected SaasMetadata.Authentication.HttpBasic httpBasic;
        @XmlElement(name = "api-key")
        protected SaasMetadata.Authentication.ApiKey apiKey;
        @XmlElement(name = "signed-url")
        protected List<SaasMetadata.Authentication.SignedUrl> signedUrl;
        @XmlElement(name = "session-key")
        protected List<SaasMetadata.Authentication.SessionKey> sessionKey;
        protected Object custom;
        @XmlAttribute(name = "profile")
        protected String profile;

        /**
         * Gets the value of the authenticator property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the authenticator property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAuthenticator().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SaasMetadata.Authentication.Authenticator }
         * 
         * 
         */
        public List<SaasMetadata.Authentication.Authenticator> getAuthenticator() {
            if (authenticator == null) {
                authenticator = new ArrayList<SaasMetadata.Authentication.Authenticator>();
            }
            return this.authenticator;
        }

        /**
         * Gets the value of the httpBasic property.
         * 
         * @return
         *     possible object is
         *     {@link SaasMetadata.Authentication.HttpBasic }
         *     
         */
        public SaasMetadata.Authentication.HttpBasic getHttpBasic() {
            return httpBasic;
        }

        /**
         * Sets the value of the httpBasic property.
         * 
         * @param value
         *     allowed object is
         *     {@link SaasMetadata.Authentication.HttpBasic }
         *     
         */
        public void setHttpBasic(SaasMetadata.Authentication.HttpBasic value) {
            this.httpBasic = value;
        }

        /**
         * Gets the value of the apiKey property.
         * 
         * @return
         *     possible object is
         *     {@link SaasMetadata.Authentication.ApiKey }
         *     
         */
        public SaasMetadata.Authentication.ApiKey getApiKey() {
            return apiKey;
        }

        /**
         * Sets the value of the apiKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link SaasMetadata.Authentication.ApiKey }
         *     
         */
        public void setApiKey(SaasMetadata.Authentication.ApiKey value) {
            this.apiKey = value;
        }

        /**
         * Gets the value of the signedUrl property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the signedUrl property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSignedUrl().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SaasMetadata.Authentication.SignedUrl }
         * 
         * 
         */
        public List<SaasMetadata.Authentication.SignedUrl> getSignedUrl() {
            if (signedUrl == null) {
                signedUrl = new ArrayList<SaasMetadata.Authentication.SignedUrl>();
            }
            return this.signedUrl;
        }

        /**
         * Gets the value of the sessionKey property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sessionKey property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSessionKey().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SaasMetadata.Authentication.SessionKey }
         * 
         * 
         */
        public List<SaasMetadata.Authentication.SessionKey> getSessionKey() {
            if (sessionKey == null) {
                sessionKey = new ArrayList<SaasMetadata.Authentication.SessionKey>();
            }
            return this.sessionKey;
        }

        /**
         * Gets the value of the custom property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getCustom() {
            return custom;
        }

        /**
         * Sets the value of the custom property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setCustom(Object value) {
            this.custom = value;
        }

        /**
         * Gets the value of the profile property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProfile() {
            return profile;
        }

        /**
         * Sets the value of the profile property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProfile(String value) {
            this.profile = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class ApiKey {

            @XmlAttribute(name = "id")
            protected String id;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;extension base="{http://xml.netbeans.org/websvc/saas/services/1.0}Authenticator"&gt;
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Authenticator
            extends org.netbeans.modules.websvc.saas.model.jaxb.Authenticator
        {

            @XmlAttribute(name = "name", required = true)
            protected String name;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="authenticator" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Authenticator"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="username" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="password" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "authenticator"
        })
        public static class HttpBasic {

            @XmlElement(required = true)
            protected org.netbeans.modules.websvc.saas.model.jaxb.Authenticator authenticator;
            @XmlAttribute(name = "username", required = true)
            protected String username;
            @XmlAttribute(name = "password", required = true)
            protected String password;

            /**
             * Gets the value of the authenticator property.
             * 
             * @return
             *     possible object is
             *     {@link org.netbeans.modules.websvc.saas.model.jaxb.Authenticator }
             *     
             */
            public org.netbeans.modules.websvc.saas.model.jaxb.Authenticator getAuthenticator() {
                return authenticator;
            }

            /**
             * Sets the value of the authenticator property.
             * 
             * @param value
             *     allowed object is
             *     {@link org.netbeans.modules.websvc.saas.model.jaxb.Authenticator }
             *     
             */
            public void setAuthenticator(org.netbeans.modules.websvc.saas.model.jaxb.Authenticator value) {
                this.authenticator = value;
            }

            /**
             * Gets the value of the username property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUsername() {
                return username;
            }

            /**
             * Sets the value of the username property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUsername(String value) {
                this.username = value;
            }

            /**
             * Gets the value of the password property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPassword() {
                return password;
            }

            /**
             * Sets the value of the password property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPassword(String value) {
                this.password = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="sign" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Sign"/&gt;
         *         &lt;element name="authenticator" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Authenticator"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="session-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="api-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="sig-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "sign",
            "authenticator"
        })
        public static class SessionKey {

            @XmlElement(required = true)
            protected Sign sign;
            @XmlElement(required = true)
            protected org.netbeans.modules.websvc.saas.model.jaxb.Authenticator authenticator;
            @XmlAttribute(name = "session-id", required = true)
            protected String sessionId;
            @XmlAttribute(name = "api-id", required = true)
            protected String apiId;
            @XmlAttribute(name = "sig-id", required = true)
            protected String sigId;
            @XmlAttribute(name = "id")
            protected String id;

            /**
             * Gets the value of the sign property.
             * 
             * @return
             *     possible object is
             *     {@link Sign }
             *     
             */
            public Sign getSign() {
                return sign;
            }

            /**
             * Sets the value of the sign property.
             * 
             * @param value
             *     allowed object is
             *     {@link Sign }
             *     
             */
            public void setSign(Sign value) {
                this.sign = value;
            }

            /**
             * Gets the value of the authenticator property.
             * 
             * @return
             *     possible object is
             *     {@link org.netbeans.modules.websvc.saas.model.jaxb.Authenticator }
             *     
             */
            public org.netbeans.modules.websvc.saas.model.jaxb.Authenticator getAuthenticator() {
                return authenticator;
            }

            /**
             * Sets the value of the authenticator property.
             * 
             * @param value
             *     allowed object is
             *     {@link org.netbeans.modules.websvc.saas.model.jaxb.Authenticator }
             *     
             */
            public void setAuthenticator(org.netbeans.modules.websvc.saas.model.jaxb.Authenticator value) {
                this.authenticator = value;
            }

            /**
             * Gets the value of the sessionId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSessionId() {
                return sessionId;
            }

            /**
             * Sets the value of the sessionId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSessionId(String value) {
                this.sessionId = value;
            }

            /**
             * Gets the value of the apiId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getApiId() {
                return apiId;
            }

            /**
             * Sets the value of the apiId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setApiId(String value) {
                this.apiId = value;
            }

            /**
             * Gets the value of the sigId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSigId() {
                return sigId;
            }

            /**
             * Sets the value of the sigId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSigId(String value) {
                this.sigId = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="sign" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Sign" minOccurs="0"/&gt;
         *         &lt;element name="authenticator" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Authenticator" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="sig-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "sign",
            "authenticator"
        })
        public static class SignedUrl {

            protected Sign sign;
            protected org.netbeans.modules.websvc.saas.model.jaxb.Authenticator authenticator;
            @XmlAttribute(name = "sig-id", required = true)
            protected String sigId;
            @XmlAttribute(name = "id")
            protected String id;

            /**
             * Gets the value of the sign property.
             * 
             * @return
             *     possible object is
             *     {@link Sign }
             *     
             */
            public Sign getSign() {
                return sign;
            }

            /**
             * Sets the value of the sign property.
             * 
             * @param value
             *     allowed object is
             *     {@link Sign }
             *     
             */
            public void setSign(Sign value) {
                this.sign = value;
            }

            /**
             * Gets the value of the authenticator property.
             * 
             * @return
             *     possible object is
             *     {@link org.netbeans.modules.websvc.saas.model.jaxb.Authenticator }
             *     
             */
            public org.netbeans.modules.websvc.saas.model.jaxb.Authenticator getAuthenticator() {
                return authenticator;
            }

            /**
             * Sets the value of the authenticator property.
             * 
             * @param value
             *     allowed object is
             *     {@link org.netbeans.modules.websvc.saas.model.jaxb.Authenticator }
             *     
             */
            public void setAuthenticator(org.netbeans.modules.websvc.saas.model.jaxb.Authenticator value) {
                this.authenticator = value;
            }

            /**
             * Gets the value of the sigId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSigId() {
                return sigId;
            }

            /**
             * Sets the value of the sigId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSigId(String value) {
                this.sigId = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="artifacts" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Artifacts" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="packageName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "artifacts"
    })
    public static class CodeGen {

        protected List<Artifacts> artifacts;
        @XmlAttribute(name = "packageName")
        protected String packageName;

        /**
         * Gets the value of the artifacts property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the artifacts property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getArtifacts().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Artifacts }
         * 
         * 
         */
        public List<Artifacts> getArtifacts() {
            if (artifacts == null) {
                artifacts = new ArrayList<Artifacts>();
            }
            return this.artifacts;
        }

        /**
         * Gets the value of the packageName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPackageName() {
            return packageName;
        }

        /**
         * Sets the value of the packageName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPackageName(String value) {
            this.packageName = value;
        }

    }

}
