//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.06 at 05:50:06 PM GMT+07:00 
//


package org.netbeans.modules.websvc.saas.model.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServletDescriptor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServletDescriptor"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="method-descriptor" type="{http://xml.netbeans.org/websvc/saas/services/1.0}MethodDescriptor" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="field-descriptor" type="{http://xml.netbeans.org/websvc/saas/services/1.0}FieldDescriptor" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="modifiers" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="class-name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="servlet-mapping" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServletDescriptor", propOrder = {
    "methodDescriptor",
    "fieldDescriptor"
})
public class ServletDescriptor {

    @XmlElement(name = "method-descriptor")
    protected List<MethodDescriptor> methodDescriptor;
    @XmlElement(name = "field-descriptor")
    protected List<FieldDescriptor> fieldDescriptor;
    @XmlAttribute(name = "modifiers")
    protected String modifiers;
    @XmlAttribute(name = "class-name")
    protected String className;
    @XmlAttribute(name = "servlet-mapping")
    protected String servletMapping;

    /**
     * Gets the value of the methodDescriptor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the methodDescriptor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMethodDescriptor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MethodDescriptor }
     * 
     * 
     */
    public List<MethodDescriptor> getMethodDescriptor() {
        if (methodDescriptor == null) {
            methodDescriptor = new ArrayList<MethodDescriptor>();
        }
        return this.methodDescriptor;
    }

    /**
     * Gets the value of the fieldDescriptor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldDescriptor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldDescriptor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FieldDescriptor }
     * 
     * 
     */
    public List<FieldDescriptor> getFieldDescriptor() {
        if (fieldDescriptor == null) {
            fieldDescriptor = new ArrayList<FieldDescriptor>();
        }
        return this.fieldDescriptor;
    }

    /**
     * Gets the value of the modifiers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiers() {
        return modifiers;
    }

    /**
     * Sets the value of the modifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiers(String value) {
        this.modifiers = value;
    }

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

    /**
     * Gets the value of the servletMapping property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServletMapping() {
        return servletMapping;
    }

    /**
     * Sets the value of the servletMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServletMapping(String value) {
        this.servletMapping = value;
    }

}
