//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.06 at 05:50:06 PM GMT+07:00 
//


package org.netbeans.modules.websvc.saas.model.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UseGenerator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UseGenerator"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="login" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="sign" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Sign" minOccurs="0"/&gt;
 *                   &lt;element name="method" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Method"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="token" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="sign" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Sign" minOccurs="0"/&gt;
 *                   &lt;element name="method" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Method"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="logout" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="sign" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Sign" minOccurs="0"/&gt;
 *                   &lt;element name="method" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Method"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UseGenerator", propOrder = {
    "login",
    "token",
    "logout"
})
public class UseGenerator {

    protected UseGenerator.Login login;
    protected UseGenerator.Token token;
    protected UseGenerator.Logout logout;

    /**
     * Gets the value of the login property.
     * 
     * @return
     *     possible object is
     *     {@link UseGenerator.Login }
     *     
     */
    public UseGenerator.Login getLogin() {
        return login;
    }

    /**
     * Sets the value of the login property.
     * 
     * @param value
     *     allowed object is
     *     {@link UseGenerator.Login }
     *     
     */
    public void setLogin(UseGenerator.Login value) {
        this.login = value;
    }

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link UseGenerator.Token }
     *     
     */
    public UseGenerator.Token getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link UseGenerator.Token }
     *     
     */
    public void setToken(UseGenerator.Token value) {
        this.token = value;
    }

    /**
     * Gets the value of the logout property.
     * 
     * @return
     *     possible object is
     *     {@link UseGenerator.Logout }
     *     
     */
    public UseGenerator.Logout getLogout() {
        return logout;
    }

    /**
     * Sets the value of the logout property.
     * 
     * @param value
     *     allowed object is
     *     {@link UseGenerator.Logout }
     *     
     */
    public void setLogout(UseGenerator.Logout value) {
        this.logout = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="sign" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Sign" minOccurs="0"/&gt;
     *         &lt;element name="method" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Method"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sign",
        "method"
    })
    public static class Login {

        protected Sign sign;
        @XmlElement(required = true)
        protected Method method;

        /**
         * Gets the value of the sign property.
         * 
         * @return
         *     possible object is
         *     {@link Sign }
         *     
         */
        public Sign getSign() {
            return sign;
        }

        /**
         * Sets the value of the sign property.
         * 
         * @param value
         *     allowed object is
         *     {@link Sign }
         *     
         */
        public void setSign(Sign value) {
            this.sign = value;
        }

        /**
         * Gets the value of the method property.
         * 
         * @return
         *     possible object is
         *     {@link Method }
         *     
         */
        public Method getMethod() {
            return method;
        }

        /**
         * Sets the value of the method property.
         * 
         * @param value
         *     allowed object is
         *     {@link Method }
         *     
         */
        public void setMethod(Method value) {
            this.method = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="sign" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Sign" minOccurs="0"/&gt;
     *         &lt;element name="method" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Method"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sign",
        "method"
    })
    public static class Logout {

        protected Sign sign;
        @XmlElement(required = true)
        protected Method method;

        /**
         * Gets the value of the sign property.
         * 
         * @return
         *     possible object is
         *     {@link Sign }
         *     
         */
        public Sign getSign() {
            return sign;
        }

        /**
         * Sets the value of the sign property.
         * 
         * @param value
         *     allowed object is
         *     {@link Sign }
         *     
         */
        public void setSign(Sign value) {
            this.sign = value;
        }

        /**
         * Gets the value of the method property.
         * 
         * @return
         *     possible object is
         *     {@link Method }
         *     
         */
        public Method getMethod() {
            return method;
        }

        /**
         * Sets the value of the method property.
         * 
         * @param value
         *     allowed object is
         *     {@link Method }
         *     
         */
        public void setMethod(Method value) {
            this.method = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="sign" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Sign" minOccurs="0"/&gt;
     *         &lt;element name="method" type="{http://xml.netbeans.org/websvc/saas/services/1.0}Method"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sign",
        "method"
    })
    public static class Token {

        protected Sign sign;
        @XmlElement(required = true)
        protected Method method;
        @XmlAttribute(name = "id", required = true)
        protected String id;

        /**
         * Gets the value of the sign property.
         * 
         * @return
         *     possible object is
         *     {@link Sign }
         *     
         */
        public Sign getSign() {
            return sign;
        }

        /**
         * Sets the value of the sign property.
         * 
         * @param value
         *     allowed object is
         *     {@link Sign }
         *     
         */
        public void setSign(Sign value) {
            this.sign = value;
        }

        /**
         * Gets the value of the method property.
         * 
         * @return
         *     possible object is
         *     {@link Method }
         *     
         */
        public Method getMethod() {
            return method;
        }

        /**
         * Sets the value of the method property.
         * 
         * @param value
         *     allowed object is
         *     {@link Method }
         *     
         */
        public void setMethod(Method value) {
            this.method = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }

}
