//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.06 at 05:50:06 PM GMT+07:00 
//


package org.netbeans.modules.websvc.saas.model.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UseTemplates complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UseTemplates"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="desktop" type="{http://xml.netbeans.org/websvc/saas/services/1.0}TemplateType" minOccurs="0"/&gt;
 *         &lt;element name="nb-module" type="{http://xml.netbeans.org/websvc/saas/services/1.0}TemplateType" minOccurs="0"/&gt;
 *         &lt;element name="web" type="{http://xml.netbeans.org/websvc/saas/services/1.0}TemplateType" minOccurs="0"/&gt;
 *         &lt;element name="web-ee7" type="{http://xml.netbeans.org/websvc/saas/services/1.0}TemplateType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UseTemplates", propOrder = {
    "desktop",
    "nbModule",
    "web",
    "webEe7"
})
public class UseTemplates {

    protected TemplateType desktop;
    @XmlElement(name = "nb-module")
    protected TemplateType nbModule;
    protected TemplateType web;
    @XmlElement(name = "web-ee7")
    protected TemplateType webEe7;

    /**
     * Gets the value of the desktop property.
     * 
     * @return
     *     possible object is
     *     {@link TemplateType }
     *     
     */
    public TemplateType getDesktop() {
        return desktop;
    }

    /**
     * Sets the value of the desktop property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemplateType }
     *     
     */
    public void setDesktop(TemplateType value) {
        this.desktop = value;
    }

    /**
     * Gets the value of the nbModule property.
     * 
     * @return
     *     possible object is
     *     {@link TemplateType }
     *     
     */
    public TemplateType getNbModule() {
        return nbModule;
    }

    /**
     * Sets the value of the nbModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemplateType }
     *     
     */
    public void setNbModule(TemplateType value) {
        this.nbModule = value;
    }

    /**
     * Gets the value of the web property.
     * 
     * @return
     *     possible object is
     *     {@link TemplateType }
     *     
     */
    public TemplateType getWeb() {
        return web;
    }

    /**
     * Sets the value of the web property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemplateType }
     *     
     */
    public void setWeb(TemplateType value) {
        this.web = value;
    }

    /**
     * Gets the value of the webEe7 property.
     * 
     * @return
     *     possible object is
     *     {@link TemplateType }
     *     
     */
    public TemplateType getWebEe7() {
        return webEe7;
    }

    /**
     * Sets the value of the webEe7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemplateType }
     *     
     */
    public void setWebEe7(TemplateType value) {
        this.webEe7 = value;
    }

}
