//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.06 at 05:50:06 PM GMT+07:00 
//


package org.netbeans.modules.websvc.saas.model.oauth;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *             specifies authorization step, that can be either
 *             1. fixed-url URL with one ore more OAuth parameters
 *             2. dynamic-url obtained during first step (request-token)
 *           
 * 
 * <p>Java class for authorizationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="authorizationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="fixed-url" type="{http://netbeans.org/ns/oauth/metadata/1}fixed-urlType"/&gt;
 *           &lt;element name="dynamic-url" type="{http://netbeans.org/ns/oauth/metadata/1}dynamic-urlType"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="param" type="{http://netbeans.org/ns/oauth/metadata/1}paramType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "authorizationType", propOrder = {
    "fixedUrl",
    "dynamicUrl",
    "param"
})
public class AuthorizationType {

    @XmlElement(name = "fixed-url")
    protected FixedUrlType fixedUrl;
    @XmlElement(name = "dynamic-url")
    protected DynamicUrlType dynamicUrl;
    protected List<ParamType> param;

    /**
     * Gets the value of the fixedUrl property.
     * 
     * @return
     *     possible object is
     *     {@link FixedUrlType }
     *     
     */
    public FixedUrlType getFixedUrl() {
        return fixedUrl;
    }

    /**
     * Sets the value of the fixedUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link FixedUrlType }
     *     
     */
    public void setFixedUrl(FixedUrlType value) {
        this.fixedUrl = value;
    }

    /**
     * Gets the value of the dynamicUrl property.
     * 
     * @return
     *     possible object is
     *     {@link DynamicUrlType }
     *     
     */
    public DynamicUrlType getDynamicUrl() {
        return dynamicUrl;
    }

    /**
     * Sets the value of the dynamicUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link DynamicUrlType }
     *     
     */
    public void setDynamicUrl(DynamicUrlType value) {
        this.dynamicUrl = value;
    }

    /**
     * Gets the value of the param property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the param property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParamType }
     * 
     * 
     */
    public List<ParamType> getParam() {
        if (param == null) {
            param = new ArrayList<ParamType>();
        }
        return this.param;
    }

}
