//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.06 at 05:50:06 PM GMT+07:00 
//


package org.netbeans.modules.websvc.saas.model.oauth;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *             specifies 3 phases of OAuth authentication mechanism:
 *             1. obtaining request-token,
 *             2. consumer authorization and getting access-token
 *             3. obtaining access-token
 *           
 * 
 * <p>Java class for flowType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="flowType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="request-token" type="{http://netbeans.org/ns/oauth/metadata/1}methodType"/&gt;
 *         &lt;element name="authorization" type="{http://netbeans.org/ns/oauth/metadata/1}authorizationType"/&gt;
 *         &lt;element name="access-token" type="{http://netbeans.org/ns/oauth/metadata/1}methodType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "flowType", propOrder = {
    "requestToken",
    "authorization",
    "accessToken"
})
public class FlowType {

    @XmlElement(name = "request-token", required = true)
    protected MethodType requestToken;
    @XmlElement(required = true)
    protected AuthorizationType authorization;
    @XmlElement(name = "access-token", required = true)
    protected MethodType accessToken;

    /**
     * Gets the value of the requestToken property.
     * 
     * @return
     *     possible object is
     *     {@link MethodType }
     *     
     */
    public MethodType getRequestToken() {
        return requestToken;
    }

    /**
     * Sets the value of the requestToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodType }
     *     
     */
    public void setRequestToken(MethodType value) {
        this.requestToken = value;
    }

    /**
     * Gets the value of the authorization property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorizationType }
     *     
     */
    public AuthorizationType getAuthorization() {
        return authorization;
    }

    /**
     * Sets the value of the authorization property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorizationType }
     *     
     */
    public void setAuthorization(AuthorizationType value) {
        this.authorization = value;
    }

    /**
     * Gets the value of the accessToken property.
     * 
     * @return
     *     possible object is
     *     {@link MethodType }
     *     
     */
    public MethodType getAccessToken() {
        return accessToken;
    }

    /**
     * Sets the value of the accessToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodType }
     *     
     */
    public void setAccessToken(MethodType value) {
        this.accessToken = value;
    }

}
