//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.06 at 05:50:06 PM GMT+07:00 
//


package org.netbeans.modules.websvc.saas.model.oauth;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for signature-methodType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="signature-methodType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="HMAC_SHA1"/&gt;
 *     &lt;enumeration value="PLAINTEXT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "signature-methodType")
@XmlEnum
public enum SignatureMethodType {

    @XmlEnumValue("HMAC_SHA1")
    HMAC_SHA_1("HMAC_SHA1"),
    PLAINTEXT("PLAINTEXT");
    private final String value;

    SignatureMethodType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SignatureMethodType fromValue(String v) {
        for (SignatureMethodType c: SignatureMethodType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
